use std::collections::HashMap;
use std::sync::Arc;
use virust_protocol::{HttpRequest, HttpResponse};

pub type HttpHandler = Arc<dyn Fn(HttpRequest) -> HttpResponse + Send + Sync>;
pub type WsHandler = Arc<dyn Fn(serde_json::Value) -> serde_json::Value + Send + Sync>;

/// Route type enum for route registry
#[derive(Debug, Clone, Copy)]
pub enum RouteType {
    WebSocket,
    HttpGet,
    HttpPost,
    HttpPut,
    HttpDelete,
}

/// Route entry for inventory-based route discovery
#[derive(Debug)]
pub struct RouteEntry {
    pub path: &'static str,
    pub route_type: RouteType,
}

inventory::collect!(RouteEntry);

#[derive(Clone)]
pub struct TypeDefinition {
    pub name: String,
    pub input_type: String,
    pub output_type: String,
}

pub struct RouteRegistry {
    http_routes: HashMap<String, HttpHandler>,
    ws_handlers: HashMap<String, WsHandler>,
    type_definitions: HashMap<String, TypeDefinition>,
}

impl RouteRegistry {
    pub fn new() -> Self {
        Self {
            http_routes: HashMap::new(),
            ws_handlers: HashMap::new(),
            type_definitions: HashMap::new(),
        }
    }

    pub fn register_http(&mut self, path: String, handler: HttpHandler) {
        self.http_routes.insert(path, handler);
    }

    pub fn register_ws(&mut self, path: String, handler: WsHandler) {
        self.ws_handlers.insert(path, handler);
    }

    pub fn register_type(&mut self, name: String, def: TypeDefinition) {
        self.type_definitions.insert(name, def);
    }

    pub fn get_http(&self, path: &str) -> Option<HttpHandler> {
        self.http_routes.get(path).cloned()
    }

    pub fn get_ws(&self, path: &str) -> Option<WsHandler> {
        self.ws_handlers.get(path).cloned()
    }

    pub fn generate_typescript(&self) -> String {
        let mut ts = String::from("// Auto-generated by Virust\n\n");

        for (_name, def) in &self.type_definitions {
            ts.push_str(&format!("export interface {} {{\n", def.input_type));
            ts.push_str(&format!("}};\n\n"));
            ts.push_str(&format!("export interface {} {{\n", def.output_type));
            ts.push_str(&format!("}};\n\n"));
        }

        ts
    }
}
