use crate::registry::{TypeDefinition, RouteRegistry};
use std::collections::HashMap;

/// TypeScript code generator
pub struct TypeScriptGenerator {
    type_definitions: HashMap<String, TypeDefinition>,
}

impl TypeScriptGenerator {
    /// Create a new TypeScript generator from type definitions
    pub fn new(type_definitions: HashMap<String, TypeDefinition>) -> Self {
        Self { type_definitions }
    }

    /// Generate TypeScript code for all registered types
    pub fn generate(&self) -> String {
        let mut ts = String::from("// Auto-generated by Virust\n\n");

        // Generate interfaces for all unique types
        let mut unique_types: std::collections::HashSet<String> = std::collections::HashSet::new();

        for (_name, def) in &self.type_definitions {
            if def.input_type != "any" && def.input_type != "void" {
                unique_types.insert(def.input_type.clone());
            }
            if def.output_type != "any" && def.output_type != "void" {
                unique_types.insert(def.output_type.clone());
            }
        }

        // Generate type interfaces
        // Note: Field-level type extraction from Rust structs is planned for future versions
        // Current implementation generates interface declarations without field definitions
        for type_name in unique_types {
            ts.push_str(&format!("export interface {} {{\n", type_name));
            ts.push_str("  // Field definitions will be added in future versions\n");
            ts.push_str("  // For now, manually define the interface fields based on your Rust structs\n");
            ts.push_str("}\n\n");
        }

        // Generate client functions
        ts.push_str("// Client functions\n\n");
        for (_name, def) in &self.type_definitions {
            self.generate_client_function(&mut ts, def);
        }

        ts
    }

    /// Generate a typed client function for a route
    fn generate_client_function(&self, ts: &mut String, def: &TypeDefinition) {
        let input_type = if def.input_type == "any" || def.input_type == "void" {
            "void".to_string()
        } else {
            def.input_type.clone()
        };

        let output_type = if def.output_type == "void" {
            "void".to_string()
        } else {
            def.output_type.clone()
        };

        ts.push_str(&format!(
            "export async function {}(req: {}): Promise<{}> {{\n",
            def.name, input_type, output_type
        ));
        ts.push_str(&format!("  return wsCall(\"{}\", req);\n", def.name));
        ts.push_str("}\n\n");
    }
}

impl From<&RouteRegistry> for TypeScriptGenerator {
    fn from(registry: &RouteRegistry) -> Self {
        Self::new(registry.get_type_definitions().clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_typescript() {
        let generator = TypeScriptGenerator::new(HashMap::new());
        let output = generator.generate();
        assert!(output.contains("// Auto-generated by Virust"));
    }

    #[test]
    fn test_generate_simple_function() {
        let mut types = HashMap::new();
        types.insert(
            "getUser".to_string(),
            TypeDefinition {
                name: "getUser".to_string(),
                input_type: "GetUserInput".to_string(),
                output_type: "User".to_string(),
            },
        );

        let generator = TypeScriptGenerator::new(types);
        let output = generator.generate();

        assert!(output.contains("export interface GetUserInput"));
        assert!(output.contains("export interface User"));
        assert!(output.contains("export async function getUser"));
    }

    #[test]
    fn test_skip_generic_types() {
        let mut types = HashMap::new();
        types.insert(
            "ping".to_string(),
            TypeDefinition {
                name: "ping".to_string(),
                input_type: "any".to_string(),
                output_type: "void".to_string(),
            },
        );

        let generator = TypeScriptGenerator::new(types);
        let output = generator.generate();

        // Should generate function but not interfaces for any/void
        assert!(output.contains("export async function ping"));
        assert!(!output.contains("export interface any"));
        assert!(!output.contains("export interface void"));
    }
}
