use crate::registry::{TypeDefinition, RouteRegistry};
use std::collections::HashMap;

/// Field information extracted from a struct
#[derive(Debug, Clone)]
struct FieldInfo {
    name: String,
    type_name: String,
    is_optional: bool,
}

/// Map a Rust type to TypeScript type
pub fn map_rust_type_to_ts(rust_type: &str) -> String {
    // Remove spaces that syn might add
    let rust_type = rust_type.replace(" ", "");

    // Handle Option<T>
    if rust_type.starts_with("Option<") {
        let inner = &rust_type[7..rust_type.len()-1];
        return format!("{} | null", map_rust_type_to_ts(inner));
    }

    // Handle Vec<T>
    if rust_type.starts_with("Vec<") {
        let inner = &rust_type[4..rust_type.len()-1];
        return format!("{}[]", map_rust_type_to_ts(inner));
    }

    // Primitive types
    match rust_type.as_str() {
        "String" | "&str" => "string".to_string(),
        "i8" | "i16" | "i32" | "i64" | "isize" |
        "u8" | "u16" | "u32" | "u64" | "usize" |
        "f32" | "f64" => "number".to_string(),
        "bool" => "boolean".to_string(),
        _ => "any".to_string(), // Fallback for complex types
    }
}

/// TypeScript code generator
pub struct TypeScriptGenerator {
    type_definitions: HashMap<String, TypeDefinition>,
}

impl TypeScriptGenerator {
    /// Create a new TypeScript generator from type definitions
    pub fn new(type_definitions: HashMap<String, TypeDefinition>) -> Self {
        Self { type_definitions }
    }

    /// Generate TypeScript code for all registered types
    pub fn generate(&self) -> String {
        let mut ts = String::from("// Auto-generated by Virust\n\n");

        // Generate interfaces for all unique types
        let mut unique_types: std::collections::HashSet<String> = std::collections::HashSet::new();

        for (_name, def) in &self.type_definitions {
            if def.input_type != "any" && def.input_type != "void" {
                unique_types.insert(def.input_type.clone());
            }
            if def.output_type != "any" && def.output_type != "void" {
                unique_types.insert(def.output_type.clone());
            }
        }

        // Generate type interfaces
        for type_name in unique_types {
            ts.push_str(&format!("export interface {} {{\n", type_name));

            // Try to find struct definition in codebase
            if let Some(fields) = self.extract_struct_fields(&type_name) {
                for field in fields {
                    let ts_type = map_rust_type_to_ts(&field.type_name);
                    let optional = if field.is_optional { "?" } else { "" };
                    ts.push_str(&format!("  {}{}: {};\n", field.name, optional, ts_type));
                }
            } else {
                ts.push_str("  // Could not extract fields\n");
            }

            ts.push_str("}\n\n");
        }

        // Generate client functions
        ts.push_str("// Client functions\n\n");
        for (_name, def) in &self.type_definitions {
            self.generate_client_function(&mut ts, def);
        }

        ts
    }

    /// Generate a typed client function for a route
    fn generate_client_function(&self, ts: &mut String, def: &TypeDefinition) {
        let input_type = if def.input_type == "any" || def.input_type == "void" {
            "void".to_string()
        } else {
            def.input_type.clone()
        };

        let output_type = if def.output_type == "void" {
            "void".to_string()
        } else {
            def.output_type.clone()
        };

        ts.push_str(&format!(
            "export async function {}(req: {}): Promise<{}> {{\n",
            def.name, input_type, output_type
        ));
        ts.push_str(&format!("  return wsCall(\"{}\", req);\n", def.name));
        ts.push_str("}\n\n");
    }

    /// Extract struct fields from a type name
    ///
    /// This is a placeholder - in production, we'd:
    /// 1. Scan source files for struct definitions
    /// 2. Parse each struct with StructParser
    /// 3. Cache results
    ///
    /// For now, return None to trigger fallback
    fn extract_struct_fields(&self, _type_name: &str) -> Option<Vec<FieldInfo>> {
        use crate::struct_parser::StructParser;

        // Placeholder implementation
        // Full implementation requires:
        // - Source file scanning infrastructure
        // - File loading and parsing
        // - Result caching
        None
    }
}

impl From<&RouteRegistry> for TypeScriptGenerator {
    fn from(registry: &RouteRegistry) -> Self {
        Self::new(registry.get_type_definitions().clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_typescript() {
        let generator = TypeScriptGenerator::new(HashMap::new());
        let output = generator.generate();
        assert!(output.contains("// Auto-generated by Virust"));
    }

    #[test]
    fn test_generate_simple_function() {
        let mut types = HashMap::new();
        types.insert(
            "getUser".to_string(),
            TypeDefinition {
                name: "getUser".to_string(),
                input_type: "GetUserInput".to_string(),
                output_type: "User".to_string(),
            },
        );

        let generator = TypeScriptGenerator::new(types);
        let output = generator.generate();

        assert!(output.contains("export interface GetUserInput"));
        assert!(output.contains("export interface User"));
        assert!(output.contains("export async function getUser"));
    }

    #[test]
    fn test_skip_generic_types() {
        let mut types = HashMap::new();
        types.insert(
            "ping".to_string(),
            TypeDefinition {
                name: "ping".to_string(),
                input_type: "any".to_string(),
                output_type: "void".to_string(),
            },
        );

        let generator = TypeScriptGenerator::new(types);
        let output = generator.generate();

        // Should generate function but not interfaces for any/void
        assert!(output.contains("export async function ping"));
        assert!(!output.contains("export interface any"));
        assert!(!output.contains("export interface void"));
    }

    #[test]
    fn test_type_mapping() {
        use super::map_rust_type_to_ts;

        assert_eq!(map_rust_type_to_ts("String"), "string");
        assert_eq!(map_rust_type_to_ts("i32"), "number");
        assert_eq!(map_rust_type_to_ts("bool"), "boolean");
        assert_eq!(map_rust_type_to_ts("Vec<String>"), "string[]");
        assert_eq!(map_rust_type_to_ts("Option<i32>"), "number | null");
    }

    #[test]
    fn test_generate_complete_interface() {
        use std::collections::HashMap;
        use crate::registry::TypeDefinition;

        let mut types = HashMap::new();
        types.insert(
            "createTodo".to_string(),
            TypeDefinition {
                name: "createTodo".to_string(),
                input_type: "CreateTodoRequest".to_string(),
                output_type: "TodoResponse".to_string(),
            },
        );

        let generator = TypeScriptGenerator::new(types);
        let output = generator.generate();

        // Should generate interface declaration
        assert!(output.contains("export interface CreateTodoRequest"));
        // Should contain fallback comment since extract_struct_fields returns None
        assert!(output.contains("// Could not extract fields"));
    }
}
