use virust_runtime::{TypeDefinition, TypeScriptGenerator};
use std::collections::HashMap;

#[test]
fn test_typescript_generation_integration() {
    // Create some sample type definitions
    let mut types = HashMap::new();

    types.insert(
        "getUser".to_string(),
        TypeDefinition {
            name: "getUser".to_string(),
            input_type: "GetUserInput".to_string(),
            output_type: "User".to_string(),
        },
    );

    types.insert(
        "createUser".to_string(),
        TypeDefinition {
            name: "createUser".to_string(),
            input_type: "CreateUserInput".to_string(),
            output_type: "User".to_string(),
        },
    );

    types.insert(
        "ping".to_string(),
        TypeDefinition {
            name: "ping".to_string(),
            input_type: "any".to_string(),
            output_type: "void".to_string(),
        },
    );

    // Generate TypeScript
    let generator = TypeScriptGenerator::new(types);
    let ts_code = generator.generate();

    // Verify the generated code contains expected elements
    assert!(ts_code.contains("// Auto-generated by Virust"));
    assert!(ts_code.contains("export interface GetUserInput"));
    assert!(ts_code.contains("export interface User"));
    assert!(ts_code.contains("export interface CreateUserInput"));
    assert!(ts_code.contains("export async function getUser"));
    assert!(ts_code.contains("export async function createUser"));
    assert!(ts_code.contains("export async function ping"));

    // Verify that generic types (any/void) don't get interfaces
    assert!(!ts_code.contains("export interface any"));
    assert!(!ts_code.contains("export interface void"));

    // Print the generated code for visual inspection
    println!("\n=== Generated TypeScript ===\n");
    println!("{}", ts_code);
    println!("=== End Generated TypeScript ===\n");
}

#[test]
fn test_type_registration() {
    // Test that we can register and retrieve types
    let def = TypeDefinition {
        name: "testFunc".to_string(),
        input_type: "TestInput".to_string(),
        output_type: "TestOutput".to_string(),
    };

    virust_runtime::register_type("testFunc".to_string(), def.clone());

    // Retrieve all registered types
    let types = virust_runtime::get_registered_types();

    // Verify our type was registered
    assert!(types.contains_key("testFunc"));
    let retrieved = types.get("testFunc").unwrap();
    assert_eq!(retrieved.name, "testFunc");
    assert_eq!(retrieved.input_type, "TestInput");
    assert_eq!(retrieved.output_type, "TestOutput");
}
