pub fn generate_typescript(
    func_name: &str,
    input_name: &str,
    input_fields: &str,
    output_name: &str,
    output_fields: &str,
) -> String {
    format!(
        r#"// Auto-generated by virust-macros
export interface {input_name} {input_fields}
export interface {output_name} {output_fields}

export function {func_name}(req: {input_name}): Promise<{output_name}> {{
    return wsCall("{func_name}", req);
}}
"#
    )
}